@startuml
'https://plantuml.com/class-diagram

Class Menu
Menu : Login()
Menu : CreateNewAccount()

Class User
User : + Saved()
User : + Logout()
User : + Watched()
User : + SwitchAccount() (nice to have)
User : + Setting() (nice to have)

Class Media
Media : + Play()
Media : + Pause()
Media : + Fastforward()
Media : + Rewind()
Media : + Fullscreen()
Media : + Subtitles()
Media : + SoundLanguage()
Media : + SoundVolume()

Interface Categories
Categories : + Action()
Categories : + Adventure()
Categories : + Age()
Categories : + Biography()
Categories : + Comedy()
Categories : + Crime()
Categories : + Drama()
Categories : + Family()
Categories : + History()
Categories : + Horror()
Categories : + Mystery()
Categories : + Rating()
Categories : + Romance()
Categories : + SciFi()
Categories : + Thriller()
Categories : + War()
Categories : + Western()

Class Film
Film : Music()
Film : Musical()
Film : Noir()
Film : Sport()

Class Serie
Serie : Animation()
Serie : Comedy()
Serie : Documentary()
Serie : TalkShow()

Class FileIO
FileIO : - Scanner scanner
FileIO : ArrayList<Film> readFilmData()
FileIO : ArrayList<Serie> readSerieData()
FileIO : displayMessage()



Menu -> User
Categories -> Film
Categories -> Serie
User -> Categories
FileIO -> Film
FileIO -> Serie
Film -> Media
Serie -> Media

@enduml